name = "Planets and Portals 3"
author = "_Shortman"
version = "Pre-release v002"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea1da5f1191201317135a73c5fbb8a2061639f0eb2d0a63a4007bf6010d41e57"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
