name = "Planets and Portals 3"
author = "_Shortman"
version = "Dev v002"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b0e293572a7cc1744f5c9dc8c69bf5b84e884d908aae56ffae74c5cef4ce65c"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
