name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.7.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c67db18718b3f982420115c69ec6dd0dd8bc97140f9b25659847df66df6ccf8e"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
