name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.6.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0fc7691dfb8294a1f485694186e0e36b3b1089b45099f5ca83587bb74027199"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
