name = "Planets and Portals 3"
author = "_Shortman"
version = "Pre-release v002"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55d6472e4bb9d6af7c5804ab8bb9cbb31fd22ad82bf66d85779e69fdb309d86a"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
