name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.7.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2a06689f87b8497af3cb7e816de671e035b7403091cff69abfc16f6b91592a6"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
