name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.8.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc4d6fcb7a84e45d256309beb29dbdbc1a74f314c2d9e407b6981b2cd474dfec"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
