name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.6.3-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b350751338f0dc7fa0acafacd3eb80af5b0cfdd9deb09e62c8f2a9d73344088"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
