name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.9.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db103508b8fa063310473c12305d1c30947f65dfddb4dd69131959c93dba908d"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"
