name = "Planets and Portals 3"
author = "_Shortman"
version = "Pre-release v006"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47b431f3053486dce142e543d99f7ee65014c89c3be77c02bb82092370a06625"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
