name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.9-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3743c43697795dfbd11248dab76c7441a7ae4f6d2505d53ae21c38ada21d881c"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
