name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.7.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be6a41fa2891d1fb2ed0cdb66519ba1475ebdb1f9dce187b65b547dd3f33d767"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
