name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.7.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8b9ce25763a2518546227fc652d111d551ea00be5169922773c43bb83c9a1fb"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
