name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.8a-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f32d49c9fb69d0f84f5d23280c121ec92ee0fd49c0e748c43300183b888595c"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
