name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.7.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77d4c0d0fe7650f71d04c7366933a380e9cdc25e1f6d9a640fae770c95528981"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
