name = "Planets and Portals 3"
author = "_Shortman"
version = "Pre-release v006"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18e25e49b020823cce58ac0db6c15e4746210d7147dac766a62506adcabf9171"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
