name = "Planets and Portals 3"
author = "_Shortman"
version = "Pre-release v002"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "084b8f14e51acf870ebd990ac791300bcde2cc6a4cf1ba2c3d8121554efa3340"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
