name = "Planets and Portals 3"
author = "_Shortman"
version = "Pre-release v006"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "332c3ecf34073b35ba78a87bf9af1b7d694c2121ff17ef276b053bf1c8e63fe4"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
