name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.8a-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2124b783eeb02985148ae22a2549529c07bae04a1d54d96535d3d93fd41a431d"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
