name = "Planets and Portals 3"
author = "_Shortman"
version = "v0.7.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4390aea49bcdd3492f2bf2edb0dc9efaa2b4e5ef1ffd0ccb9d743bb802d9646e"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
