name = "Planets and Portals 3"
author = "_Shortman"
version = "Pre-release v002"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f7d5b972da60d72a365660caa26da49a4a7435daac7fc14a58a2acb9447cdaa"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
