name = "Planets and Portals 3"
author = "_Shortman"
version = "Dev v001"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e2562c25a39dfb88e853cf09c5759bc46b30be3ef2dd6f1c179d0b6aee28a43"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
