name = "Planets and Portals 3"
author = "_Shortman"
version = "Pre-release v006"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bab1c37d47ddda3b8b7b260d61b4818e57e53bf5bfafaa9423ee71c7550c8f6"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
