name = "Planets and Portals 3"
author = "_Shortman"
version = "Pre-release v006"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7756d86d6fe7d3b30ef7ea30f3808184ef3073592357b044bff2fcbdb23c1652"

[versions]
forge = "47.3.7"
minecraft = "1.20.1"
