name = "Planets and Portals 3"
author = "_Shortman"
version = "Pre-release v006"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bde5b5df48f46c912f3d1e3c3574f8b43dc0e696b2770332aee84be6642846a4"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
