name = "Planets and Portals 3"
author = "_Shortman"
version = "Pre-release v003"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4f7b7813d7eab4700bef75ebbbb3a9d03dac3b9d1b118eac58267c82d89aaa3"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
