name = "Planets and Portals 3"
author = "_Shortman"
version = "Pre-release v005"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d6dfee2292a596573259d0600d68bec873410971abb1ef5e5ee250cadee89e2"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
