(function recipeRemovals() {
  ServerEvents.recipes((event) => {
    const recipeRemovals = [
      //! Metal Progression
      // Early game machine balancing
      { id: "create:crafting/kinetics/millstone" },
      { id: "create:crafting/kinetics/mechanical_press" },
      { id: "create:crafting/kinetics/encased_fan" },
      { id: "create:crafting/kinetics/propeller" },
      // Iron progression tweaks
      { id: "create:splashing/crushed_raw_iron" },
      { id: "create:splashing/gravel" },
      { id: "minecraft:iron_ingot_from_smelting_iron_ore" },
      { id: "minecraft:iron_ingot_from_blasting_iron_ore" },
      { id: "minecraft:iron_ingot_from_smelting_deepslate_iron_ore" },
      { id: "minecraft:iron_ingot_from_blasting_deepslate_iron_ore" },
      { id: "minecraft:iron_ingot_from_smelting_raw_iron" },
      { id: "minecraft:iron_ingot_from_blasting_raw_iron" },
      { id: "create:smelting/iron_ingot_from_crushed" },
      { id: "mekanism:processing/iron/ingot/from_dust_smelting" },
      { id: "mekanism:processing/iron/ingot/from_dust_blasting" },
      { id: "ad_astra:smelting/iron_ingot_from_smelting_moon_iron_ore" },
      { id: "ad_astra:blasting/iron_ingot_from_blasting_moon_iron_ore" },
      { id: "ad_astra:smelting/iron_ingot_from_smelting_mars_iron_ore" },
      { id: "ad_astra:blasting/iron_ingot_from_blasting_mars_iron_ore" },
      { id: "ad_astra:smelting/iron_ingot_from_smelting_mercury_iron_ore" },
      { id: "ad_astra:blasting/iron_ingot_from_blasting_mercury_iron_ore" },
      { id: "ad_astra:smelting/iron_ingot_from_smelting_glacio_iron_ore" },
      { id: "ad_astra:blasting/iron_ingot_from_blasting_glacio_iron_ore" },
      { id: "quark:tweaks/smelting/raw_iron_bricks_smelt" },
      { id: "quark:tweaks/blasting/raw_iron_bricks_blast" },
      { id: "quark:tweaks/smelting/raw_iron_block_smelt" },
      { id: "quark:tweaks/blasting/raw_iron_block_blast" },
      { id: "create:crushing/iron_ore" },
      { id: "create:crushing/deepslate_iron_ore" },
      { id: "create:crushing/moon_iron_ore" },
      { id: "create:crushing/mars_iron_ore" },
      { id: "create:crushing/mercury_iron_ore" },
      { id: "create:crushing/glacio_iron_ore" },
      { id: "create:crushing/raw_iron" },
      { id: "create:crushing/raw_iron_block" },
      { id: "create:crushing/crimsite" },
      { id: "create:crushing/crimsite_recycling" },
      // Zinc progression tweaks
      { id: "create:splashing/crushed_raw_zinc" },
      { id: "create:blasting/zinc_ingot_from_ore" },
      { id: "create:smelting/zinc_ingot_from_ore" },
      { id: "create:blasting/zinc_ingot_from_raw_ore" },
      { id: "create:smelting/zinc_ingot_from_raw_ore" },
      { id: "create:smelting/zinc_ingot_from_crushed" },
      { id: "create:crushing/zinc_ore" },
      { id: "create:crushing/deepslate_zinc_ore" },
      { id: "create:crushing/raw_zinc" },
      { id: "create:crushing/raw_zinc_block" },
      { id: "create:crushing/asurine" },
      { id: "create:crushing/asurine_recycling" },
      // Gold progression tweaks
      { id: "create:splashing/crushed_raw_gold" },
      { id: "create:crushing/nether_gold_ore" },
      { id: "create:crushing/gilded_blackstone" },
      { id: "minecraft:gold_ingot_from_smelting_gold_ore" },
      { id: "minecraft:gold_ingot_from_blasting_gold_ore" },
      { id: "minecraft:gold_ingot_from_smelting_deepslate_gold_ore" },
      { id: "minecraft:gold_ingot_from_blasting_deepslate_gold_ore" },
      { id: "minecraft:gold_ingot_from_smelting_nether_gold_ore" },
      { id: "minecraft:gold_ingot_from_blasting_nether_gold_ore" },
      { id: "minecraft:gold_ingot_from_smelting_raw_gold" },
      { id: "minecraft:gold_ingot_from_blasting_raw_gold" },
      { id: "create:smelting/gold_ingot_from_crushed" },
      { id: "mekanism:processing/gold/ingot/from_dust_smelting" },
      { id: "mekanism:processing/gold/ingot/from_dust_blasting" },
      { id: "ad_astra:smelting/gold_ingot_from_smelting_venus_gold_ore" },
      { id: "ad_astra:blasting/gold_ingot_from_blasting_venus_gold_ore" },
      { id: "quark:tweaks/smelting/raw_gold_bricks_smelt" },
      { id: "quark:tweaks/blasting/raw_gold_bricks_blast" },
      { id: "quark:tweaks/smelting/raw_gold_block_smelt" },
      { id: "quark:tweaks/blasting/raw_gold_block_blast" },
      { id: "create:crushing/gold_ore" },
      { id: "create:crushing/deepslate_gold_ore" },
      { id: "create:crushing/venus_gold_ore" },
      { id: "create:crushing/raw_gold" },
      { id: "create:crushing/raw_gold_block" },
      { id: "create:crushing/ochrum" },
      { id: "create:crushing/ochrum_recycling" },
      // Copper progression tweaks
      { id: "create:splashing/crushed_raw_copper" },
      { id: "minecraft:copper_ingot_from_smelting_copper_ore" },
      { id: "minecraft:copper_ingot_from_blasting_copper_ore" },
      { id: "minecraft:copper_ingot_from_smelting_deepslate_copper_ore" },
      { id: "minecraft:copper_ingot_from_blasting_deepslate_copper_ore" },
      { id: "minecraft:copper_ingot_from_smelting_raw_copper" },
      { id: "minecraft:copper_ingot_from_blasting_raw_copper" },
      { id: "create:smelting/copper_ingot_from_crushed" },
      { id: "mekanism:processing/copper/ingot/from_dust_smelting" },
      { id: "mekanism:processing/copper/ingot/from_dust_blasting" },
      { id: "ad_astra:smelting/copper_ingot_from_smelting_glacio_copper_ore" },
      { id: "ad_astra:blasting/copper_ingot_from_blasting_glacio_copper_ore" },
      { id: "quark:tweaks/smelting/raw_copper_bricks_smelt" },
      { id: "quark:tweaks/blasting/raw_copper_bricks_blast" },
      { id: "quark:tweaks/smelting/raw_copper_block_smelt" },
      { id: "quark:tweaks/blasting/raw_copper_block_blast" },
      { id: "create:crushing/copper_ore" },
      { id: "create:crushing/deepslate_copper_ore" },
      { id: "create:crushing/glacio_copper_ore" },
      { id: "create:crushing/raw_copper" },
      { id: "create:crushing/raw_copper_block" },
      { id: "create:crushing/veridium" },
      { id: "create:crushing/veridium_recycling" },

      //! Gemstone progression
      // Diamond
      { id: "createoreexcavation:cutting/diamond_cutting" },
      { id: "minecraft:diamond_from_smelting_diamond_ore" },
      { id: "minecraft:diamond_from_blasting_diamond_ore" },
      { id: "minecraft:diamond_from_smelting_deepslate_diamond_ore" },
      { id: "minecraft:diamond_from_blasting_deepslate_diamond_ore" },
      { id: "ad_astra:smelting/diamond_from_smelting_mars_diamond_ore" },
      { id: "ad_astra:blasting/diamond_from_blasting_mars_diamond_ore" },
      { id: "ad_astra:smelting/diamond_from_smelting_venus_diamond_ore" },
      { id: "ad_astra:blasting/diamond_from_blasting_venus_diamond_ore" },
      // Redstone
      { id: "minecraft:redstone_from_smelting_redstone_ore" },
      { id: "minecraft:redstone_from_blasting_redstone_ore" },
      { id: "minecraft:redstone_from_smelting_deepslate_redstone_ore" },
      { id: "minecraft:redstone_from_blasting_deepslate_redstone_ore" },
      { id: "regions_unexplored:redstone_from_smelting_redstone_bulb" },
      { id: "regions_unexplored:redstone_from_blasting_redstone_bulb" },
      { id: "regions_unexplored:redstone_from_smelting_raw_redstone_block" },
      { id: "regions_unexplored:redstone_from_blasting_raw_redstone_block" },
      { id: "create:crushing/redstone_ore" },
      { id: "create:crushing/deepslate_redstone_ore" },
      { id: "createoreexcavation:crushing/redstone_crushing" },
      { id: "create:filling/redstone" },
      // Emerald
      { id: "minecraft:emerald_from_smelting_emerald_ore" },
      { id: "minecraft:emerald_from_blasting_emerald_ore" },
      { id: "minecraft:emerald_from_smelting_deepslate_emerald_ore" },
      { id: "minecraft:emerald_from_blasting_deepslate_emerald_ore" },
      { id: "create:crushing/emerald_ore" },
      { id: "create:crushing/deepslate_emerald_ore" },

      //! Furnace -> Blast Furnace/Smoker migration
      { output: "minecraft:smoker" },
      { output: "minecraft:furnace" },
      { output: "minecraft:blast_furnace" },
      { id: "minecraft:coal_from_smelting_coal_ore" },
      { id: "minecraft:coal_from_smelting_deepslate_coal_ore" },
      { id: "minecraft:lapis_lazuli_from_smelting_lapis_ore" },
      { id: "minecraft:iron_nugget_from_smelting" },
      { id: "minecraft:gold_nugget_from_smelting" },
      { id: "minecraft:lapis_lazuli_from_smelting_deepslate_lapis_ore" },
      { id: "minecraft:terracotta" },
      { id: "minecraft:white_glazed_terracotta" },
      { id: "minecraft:light_gray_glazed_terracotta" },
      { id: "minecraft:gray_glazed_terracotta" },
      { id: "minecraft:black_glazed_terracotta" },
      { id: "minecraft:brown_glazed_terracotta" },
      { id: "minecraft:red_glazed_terracotta" },
      { id: "minecraft:orange_glazed_terracotta" },
      { id: "minecraft:yellow_glazed_terracotta" },
      { id: "minecraft:lime_glazed_terracotta" },
      { id: "minecraft:green_glazed_terracotta" },
      { id: "minecraft:cyan_glazed_terracotta" },
      { id: "minecraft:light_blue_glazed_terracotta" },
      { id: "minecraft:blue_glazed_terracotta" },
      { id: "minecraft:purple_glazed_terracotta" },
      { id: "minecraft:magenta_glazed_terracotta" },
      { id: "minecraft:pink_glazed_terracotta" },
      { id: "minecraft:glass" },
      { id: "minecraft:baked_potato" },
      { id: "minecraft:dried_kelp_from_smelting" },
      { id: "minecraft:cooked_beef" },
      { id: "minecraft:cooked_chicken" },
      { id: "minecraft:cooked_cod" },
      { id: "minecraft:cooked_mutton" },
      { id: "minecraft:cooked_porkchop" },
      { id: "minecraft:cooked_rabbit" },
      { id: "minecraft:cooked_salmon" },
      { id: "minecraft:popped_chorus_fruit" },
      { id: "minecraft:sponge" },
      { id: "minecraft:green_dye" },
      { id: "minecraft:lime_dye_from_smelting" },
      { id: "minecraft:stone" },
      { id: "minecraft:smooth_stone" },
      { id: "minecraft:deepslate" },
      { id: "minecraft:smooth_basalt" },
      { id: "minecraft:charcoal" },
      { id: "minecraft:smooth_quartz" },
      { id: "minecraft:smooth_sandstone" },
      { id: "minecraft:smooth_red_sandstone" },
      { id: "minecraft:cracked_stone_bricks" },
      { id: "minecraft:cracked_polished_blackstone_bricks" },
      { id: "minecraft:cracked_nether_bricks" },
      { id: "minecraft:cracked_deepslate_bricks" },
      { id: "minecraft:cracked_deepslate_tiles" },
      { id: "minecraft:brick" },
      { id: "minecraft:nether_brick" },
      { id: "minecraft:netherite_scrap" },
      { id: "minecraft:quartz" },
      { id: "ad_astra:smelting/cheese_from_smelting_moon_cheese_ore" },
      { id: "ad_astra:smelting/calorite_ingot_from_smelting_raw_calorite" },
      {
        id: "ad_astra:smelting/calorite_ingot_from_smelting_venus_calorite_ore",
      },
      {
        id: "ad_astra:smelting/calorite_ingot_from_smelting_deepslate_calorite_ore",
      },
      { id: "ad_astra:smelting/coal_from_smelting_venus_coal_ore" },
      { id: "ad_astra:smelting/coal_from_smelting_glacio_coal_ore" },
      { id: "ad_astra:smelting/lapis_lazuli_from_smelting_glacio_lapis_ore" },
      { id: "ad_astra:smelting/ice_shard_from_smelting_mars_ice_shard_ore" },
      { id: "ad_astra:smelting/ice_shard_from_smelting_moon_ice_shard_ore" },
      { id: "ad_astra:smelting/ice_shard_from_smelting_glacio_ice_shard_ore" },
      {
        id: "ad_astra:smelting/ice_shard_from_smelting_deepslate_ice_shard_ore",
      },
      { id: "ad_astra:smelting/moon_stone_from_smelting_moon_cobblestone" },
      { id: "ad_astra:smelting/mars_stone_from_smelting_mars_cobblestone" },
      { id: "ad_astra:smelting/glacio_stone_from_smelting_glacio_cobblestone" },
      { id: "ad_astra:smelting/venus_stone_from_smelting_venus_cobblestone" },
      {
        id: "ad_astra:smelting/mercury_stone_from_smelting_mercury_cobblestone",
      },
      {
        id: "ad_astra:smelting/cracked_moon_stone_bricks_from_smelting_moon_stone_bricks",
      },
      {
        id: "ad_astra:smelting/cracked_mars_stone_bricks_from_smelting_mars_stone_bricks",
      },
      {
        id: "ad_astra:smelting/cracked_glacio_stone_bricks_from_smelting_glacio_stone_bricks",
      },
      {
        id: "ad_astra:smelting/cracked_permafrost_bricks_from_smelting_permafrost_bricks",
      },
      {
        id: "ad_astra:smelting/cracked_venus_stone_bricks_from_smelting_venus_stone_bricks",
      },
      {
        id: "ad_astra:smelting/cracked_venus_sandstone_bricks_from_smelting_venus_sandstone_bricks",
      },
      {
        id: "ad_astra:smelting/cracked_mercury_stone_bricks_from_smelting_mercury_stone_bricks",
      },
      { id: "ae2:blasting/sky_stone_block" },
      { id: "ae2:smelting/silicon_from_certus_quartz_dust" },
      { id: "ae2:smelting/smooth_sky_stone_block" },
      { id: "ae2:decorative/smooth_quartz_block" },
      { id: "brewery:dumplings" },
      { id: "brewery:fried_chicken" },
      { id: "brewery:pork_knuckle" },
      { id: "brewery:sausage" },
      { id: "create:smelting/bread" },
      { id: "create:smelting/glass_from_tiled_glass" },
      { id: "create:smelting/glass_from_vertical_framed_glass" },
      { id: "create:smelting/glass_from_horizontal_framed_glass" },
      { id: "create:smelting/glass_from_framed_glass" },
      { id: "create:smelting/glass_pane_from_tiled_glass_pane" },
      { id: "create:smelting/glass_pane_from_vertical_framed_glass_pane" },
      { id: "create:smelting/glass_pane_from_horizontal_framed_glass_pane" },
      { id: "create:smelting/glass_pane_from_framed_glass_pane" },
      { id: "create:smelting/ingot_tin_compat_mekanism" },
      { id: "create:smelting/scoria" },
      { id: "croptopia:baked_beans_from_blackbean" },
      { id: "croptopia:baked_sweet_potato_from_sweetpotato" },
      { id: "croptopia:baked_yam_from_yam" },
      { id: "croptopia:caramel_from_sugar" },
      { id: "croptopia:cooked_anchovy_from_anchovy" },
      { id: "croptopia:cooked_bacon_from_bacon" },
      { id: "croptopia:cooked_calamari_from_calamari" },
      { id: "croptopia:cooked_calamari_from_glowing_calamari" },
      { id: "croptopia:cooked_shrimp_from_shrimp" },
      { id: "croptopia:cooked_tuna_from_tuna" },
      { id: "croptopia:molasses_from_sugar_cane" },
      { id: "croptopia:popcorn_from_corn" },
      { id: "croptopia:raisins_from_grape" },
      { id: "croptopia:roasted_nuts" },
      { id: "croptopia:salt_from_water_bottle" },
      { id: "croptopia:toast_from_bread" },
      { id: "mekanism:processing/bronze/ingot/from_dust_smelting" },
      { id: "mekanism:processing/tin/ingot/from_dust_smelting" },
      { id: "mekanism:processing/tin/ingot/from_ore_smelting" },
      { id: "mekanism:processing/tin/ingot/from_raw_smelting" },
      { id: "mekanism:processing/netherite/ingot_from_dust_smelting" },
      { id: "quark:building/smelting/cobblestone_to_stone_bricks" },
      { id: "quark:building/smelting/moss_paste" },
      { id: "quark:building/smelting/smooth_soul_sandstone" },
      { id: "quark:mobs/smelting/cooked_crab_leg" },
      { id: "quark:tools/smelting/trowel_to_iron_nugget" },
      { id: "quark:tweaks/smelting/bone_meal_utility" },
      { id: "quark:tweaks/smelting/clean_glass" },
      { id: "regions_unexplored:barley_smelting" },
      { id: "regions_unexplored:green_dye_from_barrel_cactus" },
      { id: "regions_unexplored:green_dye_from_saguaro_cactus" },
      { id: "regions_unexplored:mossy_stone_from_smelting_mossy_cobblestone" },
      { id: "supplementaries:ash_brick" },
      { id: "tfmg:smelting/fireproof_brick" },
      { id: "tfmg:smelting/lithium_ingot" },
      { id: "tfmg:smelting/lithium_ingot_blasting" },
      { id: "tfmg:smelting/lithium_ingot_from_crushed_blasting" },
      { id: "tfmg:smelting/nickel_ingot" },
      { id: "tfmg:smelting/nickel_ingot_blasting" },
      { id: "tfmg:smelting/nickel_ingot_from_crushed_blasting" },
      { id: "tfmg:smelting/unfinished_insulator" },

      //! Chapter 2 stuff
      //Create
      { id: "create:compacting/andesite_from_flint" },
      { id: "create:crafting/kinetics/clockwork_bearing" },
      { id: "create:crafting/kinetics/elevator_pulley" },
      { id: "create:crafting/kinetics/large_water_wheel" },
      { id: "create:crafting/kinetics/spout" },
      { id: "create:crafting/kinetics/windmill_bearing" },
      { id: "create:crafting/materials/electron_tube" },
      { id: "create:crafting/materials/rose_quartz" },
      { id: "create:sandpaper_polishing/rose_quartz" },
      { id: "create:splashing/soul_sand" },
      // TFMG
      { id: "tfmg:compacting/cast_iron" },
      { id: "tfmg:vat_machine_recipe/rubber" },

      //! Random
      // Minecraft
      { output: "minecraft:chain" },
      { output: "minecraft:ladder" },
      { output: "minecraft:bookshelf" },
      { output: "storagedrawers:oak_full_drawers_1" },
      { output: "storagedrawers:oak_full_drawers_2" },
      { output: "storagedrawers:oak_full_drawers_4" },
      { output: "storagedrawers:oak_half_drawers_1" },
      { output: "storagedrawers:oak_half_drawers_2" },
      { output: "storagedrawers:oak_half_drawers_4" },
      { input: "minecraft:andesite", type: "create:crushing" },
      { output: "minecraft:furnace_minecart", input: "minecraft:minecart" },
      { output: "minecraft:furnace_minecart", input: "minecraft:iron_ingot" },

      // Quark
      { output: "quark:blackstone_furnace" },
      { output: "quark:deepslate_furnace" },

      // Mekanism
      { output: "mekanism:ingot_steel" },
      { output: "mekanism:block_steel" },
      { output: "mekanism:enriched_iron" },
      { output: "mekanism:dust_steel" },
      { output: "mekainsm:nugget_steel" },
      { output: "mekanism:dust_refined_obsidian" },
      { output: "mekanism:alloy_infused" },
      { output: "mekanism:alloy_reinforced" },
      { output: "mekanism:alloy_atomic" },
      { output: "mekanism:diamond" },
      { output: "mekanism:refined_obsidian" },
      { output: "mekanism:teleportation_core" },

      { output: "mekanism:oredictionificator" },

      { output: "mekanism:basic_universal_cable" },
      { output: "mekanism:basic_mechanical_pipe" },
      { output: "mekanism:basic_pressurized_tube" },
      { output: "mekanism:basic_thermodynamic_conductor" },
      { output: "mekanism:diversion_transporter" },
      { output: "mekanism:restrictive_transporter" },

      { output: "mekanism:advanced_control_circuit" },
      { output: "mekanism:advanced_energy_cube" },
      { output: "mekanism:advanced_fluid_tank" },
      { output: "mekanism:advanced_chemical_tank" },
      { output: "mekanism:advanced_universal_cable" },
      { output: "mekanism:advanced_mechanical_pipe" },
      { output: "mekanism:advanced_pressurized_tube" },
      { output: "mekanism:advanced_logistical_transporter" },
      { output: "mekanism:advanced_thermodynamic_conductor" },

      { output: "mekanism:upgrade_anchor" },

      { output: "mekanism:qio_drive_array" },
      { output: "mekanism:qio_dashboard" },
      { output: "mekanism:qio_exporter" },
      { output: "mekanism:qio_importer" },
      { output: "mekanism:qio_redstone_adapter" },

      { output: "mekanism:cardboard_box" },

      {
        output: "mekanism:ingot_osmium",
        input: [
          "mekanism:raw_osmium",
          "mekanism:osmium_ore",
          "mekanism:dust_osmium",
          "mekanism:deepslate_osmium_ore",
          "create:crushed_raw_osmium",
        ],
      },
      { output: "mekanism:dust_osmium", input: "mekanism:ingot_osmium" },
      { output: "mekanism:nugget_osmium", input: "create:crushed_raw_osmium" },

      {
        output: "mekanism:ingot_lead",
        input: [
          "mekanism:raw_lead",
          "mekanism:lead_ore",
          "mekanism:dust_lead",
          "mekanism:deepslate_lead_ore",
          "create:crushed_raw_lead",
        ],
      },
      { output: "mekanism:dust_osmium", input: "mekanism:ingot_osmium" },
      { output: "mekanism:nugget_lead", input: "create:crushed_raw_lead" },

      {
        output: "mekanism:ingot_uranium",
        input: [
          "mekanism:raw_uranium",
          "mekanism:uranium_ore",
          "mekanism:dust_uranium",
          "mekanism:deepslate_uranium_ore",
          "create:crushed_raw_uranium",
        ],
      },
      { output: "mekanism:dust_uranium", input: "mekanism:ingot_uranium" },
      {
        output: "mekanism:nugget_uranium",
        input: "create:crushed_raw_uranium",
      },

      { output: "mekanism:enriched_redstone" },

      // Mekanism Generators
      { output: "mekanismgenerators:wind_generator" },
      { output: "mekanismgenerators:heat_generator" },
      { output: "mekanismgenerators:gas_burning_generator" },
      { output: "mekanismgenerators:bio_generator" },
      { output: "mekanismgenerators:advanced_solar_generator" },

      // Create
      { output: "create:framed_glass" },
      { output: "create:horizontal_framed_glass" },
      { output: "create:vertical_framed_glass" },
      { output: "create:tiled_glass" },
      { output: "create:andesite_alloy", input: "minecraft:andesite" },
      { output: "create:mechanical_crafter" },
      { output: "create:shaft" },
      { id: "create:andesite_table_cloth_from_andesite_alloy_stonecutting" },
      { id: "create:andesite_ladder_from_andesite_alloy_stonecutting" },
      { id: "create:andesite_bars_from_andesite_alloy_stonecutting" },
      { id: "create:andesite_scaffolding_from_andesite_alloy_stonecutting" },
      { id: "create:crafting/appliances/cardboard_helmet" },
      { id: "create:crafting/appliances/cardboard_chestplate" },
      { id: "create:crafting/appliances/cardboard_leggings" },
      { id: "create:crafting/appliances/cardboard_boots" },
      { id: "create:crafting/appliances/copper_backtank" },
      { id: "create:crafting/kinetics/chain_conveyor" },
      { id: "create:crafting/kinetics/steam_engine" },
      { id: "create:crafting/logistics/package_frogport" },
      { id: "create:crafting/logistics/packager" },
      { id: "create:crafting/logistics/white_postbox" },
      { id: "create:crafting/logistics/orange_postbox" },
      { id: "create:crafting/logistics/magenta_postbox" },
      { id: "create:crafting/logistics/light_blue_postbox" },
      { id: "create:crafting/logistics/yellow_postbox" },
      { id: "create:crafting/logistics/lime_postbox" },
      { id: "create:crafting/logistics/pink_postbox" },
      { id: "create:crafting/logistics/gray_postbox" },
      { id: "create:crafting/logistics/light_gray_postbox" },
      { id: "create:crafting/logistics/cyan_postbox" },
      { id: "create:crafting/logistics/purple_postbox" },
      { id: "create:crafting/logistics/blue_postbox" },
      { id: "create:crafting/logistics/brown_postbox" },
      { id: "create:crafting/logistics/green_postbox" },
      { id: "create:crafting/logistics/red_postbox" },
      { id: "create:crafting/logistics/black_postbox" },
      { id: "create:crafting/logistics/stock_link" },
      { id: "create:pressing/cardboard" },
      { id: "create:sequenced_assembly/sturdy_sheet" },

      // Create: TFMG
      { type: "tfmg:coking" },
      { type: "tfmg:industrial_blasting" },
      { type: "tfmg:winding" },
      { type: "tfmg:polarizing" },

      { id: "tfmg:casting/slag_block" },
      { id: "tfmg:crafting/kinetics/light_bulb" },
      { id: "tfmg:crafting/kinetics/steel_distillation_controller" },
      { id: "tfmg:crushing/slag_block" },
      { id: "tfmg:distillation/heavy_oil" },
      { id: "tfmg:distillation/heavy_oil_no_naphtha" },
      { id: "tfmg:distillation/heavy_oil_light_distillation" },
      { id: "tfmg:distillation/crude_oil" },
      { id: "tfmg:distillation/crude_oil_no_naphtha" },
      { id: "tfmg:distillation/crude_oil_light_distillation" },
      { id: "tfmg:sequenced_assembly/steel_mechanism" },
      { id: "tfmg:vat_machine_recipe/naphtha" },

      { id: "tfmg:crafting/kinetics/aluminum_spool" },
      { id: "tfmg:crafting/kinetics/blast_furnace_hatch" },
      { id: "tfmg:crafting/kinetics/blast_furnace_reinforcement" },
      { id: "tfmg:crafting/kinetics/blast_stove" },
      { id: "tfmg:crafting/kinetics/cast_iron_chemical_vat" },
      { id: "tfmg:crafting/kinetics/constantan_spool" },
      { id: "tfmg:crafting/kinetics/electrical_switch" },
      { id: "tfmg:crafting/kinetics/fireproof_chemical_vat" },
      { id: "tfmg:crafting/kinetics/glass_cable_insulator" },
      { id: "tfmg:crafting/kinetics/industrial_mixer" },
      { id: "tfmg:crafting/kinetics/large_pumpjack_hammer_connector" },
      { id: "tfmg:crafting/kinetics/large_pumpjack_hammer_head" },
      { id: "tfmg:crafting/kinetics/machine_input" },
      { id: "tfmg:crafting/kinetics/pumpjack_base" },
      { id: "tfmg:crafting/kinetics/pumpjack_crank" },
      { id: "tfmg:crafting/kinetics/pumpjack_hammer" },
      { id: "tfmg:crafting/kinetics/pumpjack_hammer_connector" },
      { id: "tfmg:crafting/kinetics/pumpjack_hammer_head" },
      { id: "tfmg:crafting/kinetics/rusted_blast_furnace_reinforcement" },
      { id: "tfmg:crafting/kinetics/steel_chemical_vat" },
      { id: "tfmg:crafting/kinetics/surface_scanner" },
      { id: "tfmg:crafting/kinetics/winding_machine" },
      { id: "tfmg:empty_spool_from_hardened_planks_stonecutting" },
      {
        id: "tfmg:large_pumpjack_hammer_part_from_storage_blocks_steel_stonecutting",
      },
      { id: "tfmg:mechanical_crafting/rotor" },
      {
        id: "tfmg:pumpjack_hammer_part_from_storage_blocks_steel_stonecutting",
      },
      { id: "tfmg:sequenced_assembly/generator" },
      { id: "tfmg:sequenced_assembly/motor" },
      { id: "tfmg:sequenced_assembly/potentiometer" },

      { output: "tfmg:steel_pipe" },
      { output: "tfmg:steel_distillation_output" },
      { output: "tfmg:coke_oven" },
      { output: "tfmg:blast_furnace_output" },
      { output: "tfmg:heavy_plate" },
      { output: "tfmg:electric_casing" },
      { input: "tfmg:electric_casing" },
      { output: "tfmg:copper_wire" },
      { input: "tfmg:copper_wire" },
      { output: "tfmg:aluminium_wire" },
      { input: "tfmg:copper_coil" },
      { input: "tfmg:copper_cable" },
      { output: "tfmg:cable_connector" },
      { output: "tfmg:firebox" },
      { output: "tfmg:voltmeter" },
      { output: "tfmg:energy_meter" },
      { output: "tfmg:lead_ingot" },
      { output: "tfmg:lead_sword" },
      { output: "tfmg:lead_shovel" },
      { output: "tfmg:lead_pickaxe" },
      { output: "tfmg:lead_hoe" },
      { output: "tfmg:lead_axe" },
      { output: "tfmg:lead_block" },
      { input: "tfmg:multimeter" },
      { mod: "tfmg", output: "create:crushed_raw_lead" },

      // Create: New Age
      { id: "create_new_age:shaped/basic_motor" },
      { id: "create_new_age:shaped/generator_coil" },
      { id: "create_new_age:shaped/redstone_magnet" },
      { id: "create_new_age:shaped/layered_magnet" },
      { id: "create_new_age:shaped/fluxuated_magnetite" },
      { id: "create_new_age:shaped/netherite_magnet" },
      { id: "create_new_age:shaped/electrical_connector" },
      { id: "create_new_age:shaped/electrical_connector_mirrored" },

      { output: "create_new_age:thorium" },
      { output: "create_new_age:basic_energiser" },
      { output: "create_new_age:advanced_energiser" },
      { output: "create_new_age:reinforced_energiser" },
      { output: "create_new_age:advanced_solar_heating_plate" },

      // Create Ore Excavation
      { id: "createoreexcavation:drilling_machine" },
      { id: "createoreexcavation:extractor" },
      { id: "createoreexcavation:sample_drill" },
      { id: "createoreexcavation:vein_atlas" },
      { output: "createoreexcavation:vein_finder" },
      { output: "createoreexcavation:diamond_drill" },
      { output: "createoreexcavation:netherite_drill" },
      { id: "createoreexcavation:ore_vein_type/water" },
      { mod: "createoreexcavation", output: Fluid.of("minecraft:water") },
      { id: "createoreexcavation:ore_vein_type/nether_gold" },
      { mod: "createoreexcavation", output: "minecraft:gold_nugget" },
      { id: "createoreexcavation:ore_vein_type/lapis" },
      { mod: "createoreexcavation", output: "minecraft:lapis_lazuli" },
      { id: "createoreexcavation:ore_vein_type/redstone" },
      { id: "createoreexcavation:ore_vein_type/glowstone" },
      { mod: "createoreexcavation", output: "minecraft:glowstone_dust" },
      { id: "createoreexcavation:ore_vein_type/quartz" },
      { mod: "createoreexcavation", output: "minecraft:quartz" },
      { id: "createoreexcavation:ore_vein_type/coal" },
      { mod: "createoreexcavation", output: "minecraft:coal" },
      { id: "createoreexcavation:ore_vein_type/netherite" },
      { mod: "createoreexcavation", output: "minecraft:ancient_debris" },
      { id: "createoreexcavation:ore_vein_type/diamond" },
      { id: "createoreexcavation:ore_vein_type/hardened_diamond" },
      { mod: "createoreexcavation", output: "createoreexcavation:raw_diamond" },
      { id: "createoreexcavation:ore_vein_type/gold" },
      { mod: "createoreexcavation", output: "minecraft:raw_gold" },
      { id: "createoreexcavation:ore_vein_type/copper" },
      { mod: "createoreexcavation", output: "minecraft:raw_copper" },
      { id: "createoreexcavation:ore_vein_type/zinc" },
      { mod: "createoreexcavation", output: "create:raw_zinc" },
      { id: "createoreexcavation:ore_vein_type/emerald" },
      { mod: "createoreexcavation", output: "createoreexcavation:raw_emerald" },
      { id: "createoreexcavation:ore_vein_type/iron" },
      { mod: "createoreexcavation", output: "minecraft:raw_iron" },

      // Create: Copycats+
      { input: "create:zinc_ingot", output: "copycats:copycat_shaft" },

      // Create Vintage Improvements
      { type: "vintageimprovements:polishing" },
      { type: "vintageimprovements:coiling" },
      { type: "vintageimprovements:pressurizing" },
      { type: "vintageimprovements:vacuumizing" },
      { type: "vintageimprovements:vibrating" },
      { type: "vintageimprovements:curving" },
      { type: "vintageimprovements:hammering" },
      { type: "vintageimprovements:turning" },
      { id: "vintageimprovements:craft/belt_grinder" },
      { id: "vintageimprovements:craft/centrifuge" },
      { id: "vintageimprovements:craft/curving_press" },
      { id: "vintageimprovements:craft/grinder_belt" },
      { id: "vintageimprovements:craft/laser" },
      { id: "vintageimprovements:craft/spring_coiling_machine" },
      { id: "vintageimprovements:craft/spring_coiling_machine_wheel" },
      { id: "vintageimprovements:craft/vacuum_chamber" },
      { id: "vintageimprovements:craft/vibrating_table" },
      { id: "vintageimprovements:mechanical_crafting/helve_hammer" },
      { id: "vintageimprovements:mechanical_crafting/lathe" },
      { id: "vintageimprovements:mechanical_crafting/laser" },
      { id: "vintageimprovements:sequenced_assembly/recipe_card" },
      { mod: "vintageimprovements", type: "create:pressing" },

      { id: "vintageimprovements:craft/steel_rod" },

      // AE2
      { output: "ae2:inscriber" },

      // Ad Astra
      { type: "ad_astra:nasa_workbench" },
      { type: "ad_astra:compressing" },
      { type: "ad_astra:alloying" },
      { type: "ad_astra:cryo_freezing" },
      { type: "ad_astra:refining" },

      { id: "ad_astra:rocket_nose_cone" },
      { id: "ad_astra:rocket_fin" },

      { id: "ad_astra:cable_duct" },
      { id: "ad_astra:steel_cable" },

      { output: "ad_astra:steel_ingot" },
      { output: "ad_astra:steel_block" },
      { output: "ad_astra:steel_nugget" },
      { output: "ad_astra:etrionic_blast_furnace" },
      { output: "ad_astra:fuel_refinery" },
      { output: "ad_astra:compressor" },
      { output: "ad_astra:nasa_workbench" },
      { output: "ad_astra:tier_1_rocket" },
      { output: "ad_astra:steel_plate" },
      { output: "ad_astra:steel_engine" },
      { output: "ad_astra:engine_frame" },
      { output: "ad_astra:launch_pad" },
      { output: "ad_astra:coal_generator" },
      { output: "ad_astra:desh_plate" },
      { output: "ad_astra:desh_plateblock" },
      { output: "ad_astra:desh_engine" },
      { output: "ad_astra:photovoltaic_etrium_cell" },
      { output: "ad_astra:solar_panel" },
      { output: "ad_astra:gravity_normalizer" },
      { output: "ad_astra:water_pump" },
      {
        output: "ad_astra:desh_ingot",
        input: [
          "ad_astra:raw_desh",
          "ad_astra:moon_desh_ore",
          "ad_astra:deepslate_desh_ore",
        ],
      },
      {
        output: "ad_astra:ostrum_ingot",
        input: [
          "ad_astra:raw_ostrum",
          "ad_astra:mars_ostrum_ore",
          "ad_astra:deepslate_ostrum_ore",
        ],
      },
      { output: "ad_astra:steel_rod" },
      { output: "ad_astra:oxygen_gear" },
      { output: "ad_astra:space_helmet" },
      { output: "ad_astra:space_suit" },
      { output: "ad_astra:space_pants" },
      { output: "ad_astra:space_boots" },

      // Tempad
      { mod: "tempad" },

      // Brewery
      { output: "brewery:copper_brewingstation" },
      { output: "brewery:silo_copper" },

      // Regions Unexplored
      { output: "regions_unexplored:raw_redstone_block" },

      // Grapple Mod
      { output: "grapplemod:repeller" },
      { output: "grapplemod:forcefieldupgradeitem" },
    ];

    recipeRemovals.forEach((recipe) => {
      event.remove(recipe);
    });
  });
})();
